packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  workerd: true
  sharp: true

minimumReleaseAgeExclude:
  - "@cloudflare/workers-types@5.20260930.2"
  - "@cloudflare/workerd-darwin-64@1.20260930.2"
  - "@cloudflare/workerd-darwin-arm64@1.20260930.2"
  - "@cloudflare/workerd-linux-64@1.20260930.2"
  - "@cloudflare/workerd-linux-arm64@1.20260930.2"
  - "@cloudflare/workerd-windows-64@1.20260930.2"
  - miniflare@5.20260930.0-alpha
  - workerd@1.20260930.2
  - wrangler@4.145.0

patchedDependencies:
  "@cloudflare/ci@0.2.0": patches/@cloudflare__ci@0.2.0.patch
